name: cairodart
description: Dart bindings for Cairo library.
version: 0.2.3
author: Alexander Dembinsky <alexander.dembinsky@gmail.com>
homepage: https://github.com/alexander-dembinsky/cairodart

environment:
  sdk: '>=2.8.1 <3.0.0'

dev_dependencies:
  test: any
