name: cairodart
description: >
  Dart bindings for Cairo library.
version: 0.2.1
author: Alexander Dembinsky <alexander.dembinsky@gmail.com>
homepage: https://github.com/alexander-dembinsky/cairodart
dev_dependencies:
  test: any
